Packer base
Otus-DevOps-2023-05/PavelBaburov_infra pull request #5
Opened 2023-07-24 16:51 UTC by PavelBaburov

# Выполнено ДЗ № 07 Packer

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
1) Создан файл ubuntu16.json для создания reddit-base образа.
2) Создан файл ubuntu16_template.json и variables.json (variables.json.example) для создания reddit-base образа с переменными вынесенными в отдельный файл.

Задание со звёздочкой
Файл immutable.json использует переменные из файла variables.json (variables.json.example) и использует следующие файлы:
- files/reddit.service - копируется в образ для настройки работы reddit как сервиса;
- scripts/install_ruby.sh - усатновка rubby;
- scripts/install_mongodb.sh - установка mongodb;
- files/deploy.sh - установка reddit и регистрация сервиса.

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2023-07-24 16:53 UTC, PavelBaburov commented
сейчас переделаю, чтоб тест проходил

2023-07-24 17:03 UTC, PavelBaburov commented
теперь на ругается на путь к key файл, который я вынес в variables.json

2023-07-24 17:43 UTC, PavelBaburov commented
дописал в ReadMe про create-reddit-vm.sh

2023-07-26 16:19 UTC, mrgreyves requested changes
Здравствуйте!)
Вам нужно добавить фейковый ключик в репозиторий
ДЗ возвращаю на доработку

2023-07-26 21:06 UTC, PavelBaburov commented
Приветствую,
Ясно, сначала не понял, что этот файл нужен. :-)

2023-07-31 08:02 UTC, mrgreyves approved these changes
Здравствуйте!)
Проверил ваше дз
Все задания выполнены корректно
ДЗ принимаю =)

2023-07-31 16:52 UTC, merged